### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by ydv-ankit** [tonic-6101/cheat-sheets#1]
hey there, i got to know you are looking for collaboration??
I think we can build something great together

**Comment by tonic-6101** [comment]
Hi, for sure we would appreciate the collaboration with you. Do you already have a suggestion?

**Comment by ydv-ankit** [comment]
no reply

**Comment by ydv-ankit** [comment]
i need to know for what i can collaborate and give suggestions

**Comment by tonic-6101** [comment]
Hey,

How's it going? I wanted to drop a message and apologise for the recent misunderstanding. I'm really keen to keep collaborating with you on the Gotcha repository because it's a project I'm super passionate about and I know you've got skills that can take it to the next level.

Let's make sure we keep the lines of communication open from here on out, and if you ever have any concerns or questions, don't hesitate to reach out. I'm always here to help.

Thanks again for all the work you've put in so far. I'm really excited to see what we can achieve together.

Cheers
